borders: Rounded
colors:
  text: '#070707'
  text_special: '#000000'
  text_secondary: '#3F3F3F'
  text_error: '#171717'
  outline: '#9F9F9F'
  outline_selected: '#2C2C2C'
  outline_hover: '#474747'
  outline_secondary: '#7F7F7F'
  message_outline: '#0F0F0F'
  message_error_outline: '#272727'
  message_success_outline: '#1F1F1F'
  command_capture: '#000000'
  item_info:
    tag: '#878787'
    title: '#0A0A0A'
    description: '#575757'
    author: '#171717'
    viewcount: '#4F4F4F'
    length: '#2F2F2F'
    published: '#676767'
    video_count: '#1F1F1F'
    sub_count: '#373737'
    likes: '#0F0F0F'
    genre: '#474747'
    page_turner: '#8F8F8F'
